spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:Testing}?createDatabaseIfNotExist=true&sessionVariables=sql_mode=''
    username: ${DB_USER:backoffice}
    password: ${DB_PASSWORD:Backoffice1!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show_sql: true
    format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: ${TOMCAT_PORT:8084}